name = "BeyondNothing"
license = "MIT"
licenselink = "https://github.com/salcan/BeyondNothing/blob/master/LICENSE"
description = "Simplest Hugo theme possible"
homepage = ""
min_version = 0.14
tags = ["blog", "lander", "minimalist", "clean"]
features = "nothing yet"

[author]
  name = "Jeremy"
  homepage = ""
